name: Music CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps
        run: npm ci

      - name: test
        run: npm run test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    environment: 
        name: demo
        url: ${{ steps.deploy_to_pages.outputs.github_pages_url}}

    permissions:
      contents: read
      pages: write
      id-token: write

    concurrency:
        group: "pages"
        cancel-in-progress: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Vite Deploy
        uses: skywarth/vite-github-pages-deployer@master
        id: deploy_to_pages